apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - image: d4rthvadr/t-acme-expiration
          name: expiration
          resources:
            requests:
              cpu: "20m"
              memory: "55M"
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: "dev"
            - name: NATS_URL
              value: "nats://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: "ticketing"
            - name: REDIS_HOST
              value: "expiration-redis-srv"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      restartPolicy: Always
