apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - image: mistykraken/tickets
          name: tickets
          resources:
            requests:
              cpu: "20m"
              memory: "55M"
          livenessProbe:
            httpGet:
              path: /_status/healthz
              port: 3002
            initialDelaySeconds: 90
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /_status/healthz
              port: 3002
            initialDelaySeconds: 30
            timeoutSeconds: 10
          ports:
            - containerPort: 3002
              name: tickets-port
          imagePullPolicy: Never
          env:
            - name: DB_MONGO_URL
              value: mongodb://tickets-mongo-srv:27017/tickets
            - name: NODE_PORT
              value: "3002"
            - name: NODE_ENV
              value: "dev"
            - name: NATS_URL
              value: "nats://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: "ticketing"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            # - name: JWT_SECRET
            #   valueFrom:
            #     secretKeyRef:
            #       name: jwt-secret
            #       key: JWT_KEY

      restartPolicy: Always

---
kind: Service
apiVersion: v1
metadata:
  name: tickets-srv
spec:
  selector:
    app: tickets
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
