apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

replicas:
  - name: tickets-deployment
    count: 2
  - name: orders-deployment
    count: 1
  - name: auth-deployment
    count: 1
  - name: payments-deployment
    count: 1
  - name: expiration-deployment
    count: 1
  - name: client-deployment
    count: 1
