name: deploy-auth
on:
  push:
    branches:
      - main
    paths:
      - "auth/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: auth
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./auth # Point to the auth directory
          file: ./auth/Dockerfile # Path to the Dockerfile relative to repo root
          push: true
          tags: |
            d4rthvadr/t-acme-auth
            d4rthvadr/t-acme-auth:${{ github.sha }}
