name: orders-tests

on:
  push:
    branches: ["main"]
    paths:
      - "orders/**"

  pull_request:
    branches: ["main"]
    paths:
      - "orders/**"

  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test-template.yml
    with:
      service: orders
