name: payments-tests

on:
  push:
    branches: ["main"]
    paths:
      - "payments/**"

  pull_request:
    branches: ["main"]
    paths:
      - "payments/**"

  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test-template.yml
    with:
      service: payments
