name: tickets-deploy
on:
  push:
    branches: ["main"]
    paths:
      - "tickets/**"

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: main
    defaults:
      run:
        working-directory: tickets
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./tickets # Point to the tickets directory
          file: ./tickets/Dockerfile # Path to the Dockerfile relative to repo root
          push: true
          platforms: linux/amd64
          tags: |
            d4rthvadr/t-acme-tickets
            d4rthvadr/t-acme-tickets:${{ github.sha }}
          cache-from: type=registry,ref=d4rthvadr/t-acme-tickets:buildcache
          cache-to: type=registry,ref=d4rthvadr/t-acme-tickets:buildcache,mode=max

      - name: Deploy to digitalocean
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}

      - name: Fetch kubeconfig for the cluster
        run: doctl k8s cluster kubeconfig save "${{ vars.CLUSTER_ENV_NAME}}"

      - name: Deploy to Kubernetes
        run: kubectl rollout restart deployment tickets-deployment
