name: tickets-tests

on:
  push:
    branches: ["main"]
    paths:
      - "tickets/**"
  pull_request:
    branches: ["main"]
    paths:
      - "tickets/**"

  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test-template.yml
    with:
      service: tickets
